project:
  type: website

website:
  title: "Prof. Luís Felipe Amaral"
  navbar:
    pinned: true
    left:
      - href: about.qmd
        text: Sobre

      - href: notes.qmd
        text: Escritos matemáticos

      - href: books.qmd
        text: Livros

      - href: latex.qmd
        text: Arquivos LaTeX
    right:
      - icon: github
        href: https://github.com/luisfelipesamaral

      - icon: envelope
        href: mailto:lfamaral.math@gmail.com

  page-footer:
    left: "© 2026, Luís Felipe Amaral"
    right: "Desenvolvido com [Quarto®](https://quarto.org)"

  back-to-top-navigation: true
  reader-mode: true

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link rel="stylesheet"
                href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">


