---
title: "Textos Matemáticos"
---

# Dissertação de Mestrado

**Título:** "Estudo da dinâmica local das aplicações de Hénon cúbicas conservativas"

**Resumo:** O objetivo do presente trabalho é apresentar um estudo dos aspectos locais da dinâmica da família de aplicações de Hénon cúbicas conservativas em torno dos seus pontos fixos, que podem ser hiperbólicos, hiperbólicos reversos, elípticos ou parabólicos. Serão utilizadas as definições de estabilidade e instabilidade segundo J. K. Moser. Nos casos hiperbólico e hiperbólico reverso, provaremos que todo difeomorfismo é instável em seu ponto fixo, usando o Teorema de Hartman--Grobman. Mostraremos, no primeiro caso, a existência de pontos homoclínicos topologicamente transversos para uma grande parcela da família em questão. Por conseguinte, as aplicações que satisfazem esta condição são caóticas perto do ponto fixo. Já no caso elíptico, provaremos que as aplicações são estáveis em todos os pontos fixos não-ressonantes até a sexta ordem, onde utilizaremos os Teoremas da Forma Normal de Birkhoff e do Twist de Moser. Para o caso parabólico, demonstraremos que as aplicações da família referida são instáveis no ponto fixo, de acordo com um critério estabelecido por T. Levi-Civita, com exceção de duas, que não se pode afirmar quanto à estabilidade delas.

[📄 Baixar PDF](pdf/Dissertacao_HenonCubicoConservativo.pdf){.btn .btn-primary}

# Tese de doutorado

**Título:** "Contributions to the continuity problem of Lyapunov exponents for linear cocycles over hyperbolic base maps"

**Resumo:** Vamos fixar um sistema dinâmico composto por um homeomorfismo hiperbólico $f\colon M\to M$ definido em um espaço métrico compacto munido de uma probabilidade $\mu$ que seja $f$-ergódica e que possua estrutura de produto local e suporte total.
Dada uma aplicação contínua $B\colon M\to\mathrm{GL}(2,\mathbb{R})$ (isto é, cada elemento da imagem é uma transformação linear $\mathbb{R}^2\to\mathbb{R}^2$ invertível), podemos construir seu cociclo linear $F_B\colon M\times\mathbb{R}^2\to M\times\mathbb{R}^2$ como sendo $F_B(x, v)=(f(x), B(x)\cdot v)$.
Uma ferramenta muito útil para caracterizar o sistema dinâmico gerado pelo cociclo linear sobre o fibrado $M\times\mathbb{R}^2$ são os chamados \textit{expoentes de Lyapunov}: $\lambda_+(B)$ e $\lambda_-(B)$, constantes em $\mu$-quase todo ponto (e, portanto, dependendo apenas da aplicação $B$ que gera o cociclo linear).
Ainda não sabemos responder qual o maior conjunto possível de aplicações contínuas $M\to\mathrm{GL}(2,\mathbb{R})$ no qual os expoentes de Lyapunov variam continuamente.
Para este fim, verifica-se que é suficiente considerar aplicações $M\to\mathrm{SL}(2,\mathbb{R})$ (ou seja, cujos elementos da imagem sejam transformações lineares $\mathbb{R}^2\to\mathbb{R}^2$ que preservam áreas).
Essas aplicações são importantes devido ao fato de que seus expoentes de Lyapunov são números opostos.
O pesquisador Marcelo Viana afirma, em uma de suas conjecturas, que os expoentes de Lyapunov serão contínuos no espaço das aplicações contínuas $B\colon M\to\mathrm{SL}(2,\mathbb{R})$ que admitem ao menos uma holonomia uniforme (coleção de isomorfismos lineares entre fibras de um mesmo conjunto estável/instável local, que são conjugados à aplicação $B$ nestes conjuntos e que variam continuamente com as fibras).
Apesar de já termos alguns resultados parciais com relação a esta conjectura, ela ainda se encontra em aberto.
Nosso objetivo no presente trabalho é dar algumas contribuições ao problema da continuidade, com vistas a uma solução definitiva.

Para os resultados aqui apresentados, nós precisaremos de dois conceitos importantes.
O primeiro deles é a *condição de $2$-invariância* de um cociclo linear munido de uma holonomia estável uniforme: de forma sucinta, esse cociclo admite duas secções $M\to\mathbb{PR}^2$ contínuas, transversais e invariantes tanto pelo cociclo quanto pela holonomia (com suas versões projetivas).
E o outro conceito é a *condição de equiproximidade* de uma sequência de holonomias instáveis: os isomorfismos lineares que compõem cada holonomia estão em uma vizinhança uniforme da identidade, desde que as fibras estejam suficientemente próximas.
Essa condição é suficiente para concluirmos a existência de uma subsequência convergente dessas holonomias instáveis (uma versão do famoso Teorema de Arzelá--Ascoli para holonomias), o que nos permite abrir mão de que as holonomias precisam convergir para que o cociclo linear em questão seja um ponto de continuidade para os expoentes de Lyapunov.
Dito isso, mostra-se neste trabalho que, dada uma sequência de cociclos lineares admitindo uma holonomia estável uniforme e uma holonomia instável (tanto uniforme quanto não-uniforme) de modo que os cociclos lineares convirjam (com holonomia estável) para um cociclo linear que satisfaz a condição de $2$-invariância, e a sequência formada pelas holonomias instáveis satisfazem a condição de equiproximidade, então há a convergência dos expoentes de Lyapunov.
Prova-se ainda que, substituindo a hipótese da sequência de holonomias instáveis satisfazerem a condição de equiproximidade por uma convergência uniforme em um conjunto de medida positiva, podemos afirmar que, se os expoentes de Lyapunov do cociclo linear limite forem não-nulos, então todo expoente de Lyapunov da sequência passa a ser também não-nulo a partir de algum elemento.
Esse é o passo inicial para se mostrar a continuidade.

[📄 Baixar PDF](pdf/Tese_ContributionsToTheContinuityProblem.pdf){.btn .btn-primary}